In [1]:
import pandas as pd
import numpy as np
import math
import random

In [2]:
df=pd.read_csv("16P.csv",encoding="ISO-8859-1") #use encoding for avoid from errors
df

Response Id  You regularly make new friends.  \
0                0                                0   
1                1                                0   
2                2                                0   
3                3                                0   
4                4                                0   
...            ...                              ...   
59994        59994                                0   
59995        59995                                0   
59996        59996                                0   
59997        59997                                0   
59998        59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                                      0                                            
3                                                     -1                                            
4                                                      0                                            
...                                                  ...                                            
59994                                                 -1                                            
59995                                                  0                                            
59996                                                  0                                            
59997                                                  0                                            
59998                                                  0                                            

       Seeing other people cry can easily make you feel like you want to cry too  \
0                                                      0                           
1                                                     -2                           
2                                                      2                           
3                                                      3                           
4                                                     -1                           
...                                                  ...                           
59994                                                  0                           
59995                                                 -2                           
59996                                                  1                           
59997                                                  1                           
59998                                                  2                           

       You often make a backup plan for a backup plan.  \
0                                                    0   
1                                                   -3   
2                                                    0   
3                                                   -1   
4                                                    0   
...                                                ...   
59994                                               -3   
59995                                                1   
59996                                                0   
59997                                               -1   
59998                                                0   

       You usually stay calm, even under a lot of pressure  \
0                                                      0     
1                                                     -1     
2                                                     -1     
3                                                      0     
4                                                      2     
...                                                  ..

In [3]:
types = np.unique(np.array(df['Personality']))
types

array(['ENFJ', 'ENFP', 'ENTJ', 'ENTP', 'ESFJ', 'ESFP', 'ESTJ', 'ESTP',
       'INFJ', 'INFP', 'INTJ', 'INTP', 'ISFJ', 'ISFP', 'ISTJ', 'ISTP'],
      dtype=object)

In [4]:
df.drop("Response Id",axis=1,inplace=True) #drop the unnecessary column

In [5]:
df["Personality"]=df["Personality"].str.replace("ESTJ","0")
df["Personality"]=df["Personality"].str.replace("ENTJ","1")
df["Personality"]=df["Personality"].str.replace("ESFJ","2")
df["Personality"]=df["Personality"].str.replace("ENFJ","3")
df["Personality"]=df["Personality"].str.replace("ISTJ","4")
df["Personality"]=df["Personality"].str.replace("ISFJ","5")
df["Personality"]=df["Personality"].str.replace("INTJ","6")
df["Personality"]=df["Personality"].str.replace("INFJ","7")
df["Personality"]=df["Personality"].str.replace("ESTP","8")
df["Personality"]=df["Personality"].str.replace("ESFP","9")
df["Personality"]=df["Personality"].str.replace("ENTP","10")
df["Personality"]=df["Personality"].str.replace("ENFP","11")
df["Personality"]=df["Personality"].str.replace("ISTP","12")
df["Personality"]=df["Personality"].str.replace("ISFP","13")
df["Personality"]=df["Personality"].str.replace("INTP","14")
df["Personality"]=df["Personality"].str.replace("INFP","15")

In [6]:
df

You regularly make new friends.  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   
...                                ...   
59994                                0   
59995                                0   
59996                                0   
59997                                0   
59998                                0   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                      0                                            
1                                                      0                                            
2                                                      0                                            
3                                                     -1                                            
4                                                      0                                            
...                                                  ...                                            
59994                                                 -1                                            
59995                                                  0                                            
59996                                                  0                                            
59997                                                  0                                            
59998                                                  0                                            

       Seeing other people cry can easily make you feel like you want to cry too  \
0                                                      0                           
1                                                     -2                           
2                                                      2                           
3                                                      3                           
4                                                     -1                           
...                                                  ...                           
59994                                                  0                           
59995                                                 -2                           
59996                                                  1                           
59997                                                  1                           
59998                                                  2                           

       You often make a backup plan for a backup plan.  \
0                                                    0   
1                                                   -3   
2                                                    0   
3                                                   -1   
4                                                    0   
...                                                ...   
59994                                               -3   
59995                                                1   
59996                                                0   
59997                                               -1   
59998                                                0   

       You usually stay calm, even under a lot of pressure  \
0                                                      0     
1                                                     -1     
2                                                     -1     
3                                                      0     
4                                                      2     
...                                                  ...     
59994                                                 -2     
59995                                                  3     
59996                    

In [7]:
df_normalize=df.copy()  #create a normalize function for get values between 0 and 1
def normalization(row):
    minimum=min(row)
    maximum=max(row)
    value=(row-minimum)/(maximum-minimum)
    return value
for column in df_normalize.columns[:-1]:
    arr=np.array(df_normalize[column])
    df_normalize[column]=normalization(arr)
df_normalize

You regularly make new friends.  \
0                             0.666667   
1                             0.666667   
2                             0.666667   
3                             0.666667   
4                             0.666667   
...                                ...   
59994                         0.666667   
59995                         0.666667   
59996                         0.666667   
59997                         0.666667   
59998                         0.666667   

       You spend a lot of your free time exploring various random topics that pique your interest  \
0                                                    0.5                                            
1                                                    0.5                                            
2                                                    0.5                                            
3                                                    0.0                                            
4                                                    0.5                                            
...                                                  ...                                            
59994                                                0.0                                            
59995                                                0.5                                            
59996                                                0.5                                            
59997                                                0.5                                            
59998                                                0.5                                            

       Seeing other people cry can easily make you feel like you want to cry too  \
0                                               0.500000                           
1                                               0.166667                           
2                                               0.833333                           
3                                               1.000000                           
4                                               0.333333                           
...                                                  ...                           
59994                                           0.500000                           
59995                                           0.166667                           
59996                                           0.666667                           
59997                                           0.666667                           
59998                                           0.833333                           

       You often make a backup plan for a backup plan.  \
0                                             0.500000   
1                                             0.000000   
2                                             0.500000   
3                                             0.333333   
4                                             0.500000   
...                                                ...   
59994                                         0.000000   
59995                                         0.666667   
59996                                         0.500000   
59997                                         0.333333   
59998                                         0.500000   

       You usually stay calm, even under a lot of pressure  \
0                                               0.500000     
1                                               0.333333     
2                                               0.333333     
3                                               0.500000     
4                                               0.833333     
...                                                  ...     
59994                                           0.166667     
59995                                           1.000000     
59996                    

In [8]:
df_normalize = df_normalize.sample(frac=1) #use sample function for shuffle the data
X = np.array(df_normalize.drop(["Personality"],axis=1)) #decide dependet variable
y = np.array(df_normalize["Personality"].astype("int")) #decide independent variable
testx = list(np.array_split(X,5)) #split the data for take each fold
testy = list(np.array_split(y,5))
X_test = testx[0] #test data is one of this split
y_test = testy[0]
testx.pop(0)  #use pop for elimine test data from all data
testy.pop(0)
X_train = np.concatenate(testx) #train data is rest of this slpit
y_train = np.concatenate(testy)

In [9]:
def distances(X_test, X_train): #create distance function for calculate euqlidead distance of each row
    distance = -2 * np.dot(X_test, X_train.T) + np.sum(X_train**2,    axis=1) + np.sum(X_test**2, axis=1)[:, np.newaxis]
    distance=np.sqrt(distance)
    return distance

distance=distances(X_test,X_train)
print(distance)

[[2.1602469  2.40370085 2.80871659 ... 2.04124145 2.91547595 2.10818511]
 [2.14734979 2.34520788 2.18581284 ... 2.98142397 2.71825107 2.68741925]
 [2.41522946 2.75882423 2.80871659 ... 2.4832774  3.03681119 2.44948974]
 ...
 [2.24227067 2.74367961 2.61937227 ... 2.62995564 2.81365717 2.20479276]
 [2.24845626 2.62466929 2.61406452 ... 3.09120617 3.01846171 2.72845092]
 [2.3570226  2.54950976 3.         ... 2.43812314 3.01846171 2.51661148]]


In [10]:
def K_Neighbors(train, test, num): #knn algorith for find the nearest neighbor i sort my list in this function for find the 
    neighbors=[]                   #prediction at the same time, it will return prediction
    distance=distances(test,train)
    sorted_dist=distance.argsort()
    for dist in sorted_dist:
        data  = y_train[dist]
        neighbors.append(data[:num])
    return neighbors
K_Neighbors(X_train, X_test, 1)

[array([7]),
 array([6]),
 array([14]),
 array([4]),
 array([8]),
 array([15]),
 array([13]),
 array([9]),
 array([7]),
 array([7]),
 array([11]),
 array([2]),
 array([5]),
 array([5]),
 array([1]),
 array([13]),
 array([12]),
 array([11]),
 array([10]),
 array([15]),
 array([12]),
 array([13]),
 array([1]),
 array([1]),
 array([8]),
 array([13]),
 array([5]),
 array([9]),
 array([8]),
 array([1]),
 array([8]),
 array([0]),
 array([7]),
 array([2]),
 array([9]),
 array([6]),
 array([14]),
 array([1]),
 array([0]),
 array([5]),
 array([0]),
 array([6]),
 array([8]),
 array([0]),
 array([12]),
 array([1]),
 array([15]),
 array([9]),
 array([8]),
 array([2]),
 array([0]),
 array([15]),
 array([2]),
 array([11]),
 array([14]),
 array([15]),
 array([8]),
 array([11]),
 array([11]),
 array([7]),
 array([10]),
 array([3]),
 array([0]),
 array([15]),
 array([6]),
 array([4]),
 array([11]),
 array([7]),
 array([3]),
 array([3]),
 array([11]),
 array([15]),
 array([4]),
 array([2]),
 array([5]),

In [11]:
prediction = K_Neighbors(X_train, X_test, 1)
def confusion_matrix(true, pred): #confusion matrix for find tp,tn,fp,fn values

  K = len(np.unique(true)) # Number of classes 
  result = np.zeros((K, K)) #zeros matrix

  for i in range(len(true)): #implement our prediction in confusion matrix
    result[true[i]][pred[i]] += 1

  return result
print(confusion_matrix(y_test,prediction))

[[704.   1.   0.   1.   0.   0.   1.   0.   0.   1.   4.   2.   0.   0.
    2.   2.]
 [  2. 779.   4.   2.   0.   3.   0.   0.   1.   3.   2.   0.   1.   0.
    5.   3.]
 [  1.   2. 709.   0.   1.   0.   3.   0.   0.   1.   1.   0.   1.   1.
    1.   3.]
 [  2.   0.   1. 729.   0.   0.   1.   1.   0.   1.   1.   2.   3.   4.
    3.   0.]
 [  2.   0.   0.   0. 708.   1.   2.   2.   0.   0.   3.   2.   2.   0.
    2.   2.]
 [  1.   0.   0.   1.   0. 689.   0.   1.   1.   1.   0.   1.   3.   2.
    1.   5.]
 [  0.   0.   0.   3.   4.   1. 802.   0.   0.   2.   1.   5.   1.   1.
    0.   3.]
 [  3.   3.   0.   2.   1.   1.   2. 739.   1.   0.   0.   0.   0.   0.
    3.   1.]
 [  2.   2.   1.   1.   0.   1.   3.   0. 701.   0.   0.   1.   0.   0.
    0.   2.]
 [  2.   2.   0.   1.   0.   2.   1.   2.   2. 706.   0.   0.   2.   0.
    1.   1.]
 [  1.   1.   2.   2.   1.   2.   1.   1.   0.   3. 728.   0.   0.   2.
    3.   2.]
 [  3.   0.   1.   1.   1.   2.   1.   2.   1.   3.   1. 741.   0

In [12]:
matrix=confusion_matrix(y_test,prediction)
def evaluate(matrix,k): #create a evulate function for calculate aur percentage acuarcy,recall and precision values
    accuracy = 0        # by using confusion matrix for this calculations
    precision = 0
    recall = 0
    for i in range(np.shape(matrix)[0]):
        tp = matrix[i, i]
        fp = np.sum(matrix[i]) - tp
        fn = np.sum(matrix[:, i]) - tp
        tn = np.sum(matrix) - tp - fp - fn
        acc = (tp + tn) / (tp + fp + fn + tn)
        accuracy += acc
        prec = tp / (tp + fp)
        precision += prec
        rec = tp / (tp + fn)
        recall += rec
    print("\nFor k: {} ".format(k))
    print("Accuracy: %", round((accuracy / 16) * 100, 2),end="")
    print(" Precision: %", round((precision / 16) * 100, 2),end="")
    print(" Recall: %", round((recall / 16) * 100, 2),end="")
evaluate(matrix,1)


For k: 1 
Accuracy: % 99.68 Precision: % 97.43 Recall: % 97.43

In [13]:
for i in range(5): # calculate this value for each fold
    X = np.array(df_normalize.drop(["Personality"],axis=1))
    y = np.array(df_normalize["Personality"].astype("int"))
    testx = list(np.array_split(X,5))
    testy = list(np.array_split(y,5))
    X_test = testx[i]
    y_test = testy[i]
    testx.pop(i)
    testy.pop(i)
    X_train = np.concatenate(testx)
    y_train = np.concatenate(testy)
    k_list=[1,3,5,7,9] #calculate this value for each k value
    print("\n\nFold {}".format(i+1))
    for k in k_list:
        prediction = K_Neighbors(X_train, X_test, k)
        matrix=confusion_matrix(y_test,prediction)
        evaluate(matrix,k)
    



Fold 1

For k: 1 
Accuracy: % 99.68 Precision: % 97.43 Recall: % 97.43
For k: 3 
Accuracy: % 99.27 Precision: % 94.19 Recall: % 94.2
For k: 5 
Accuracy: % 98.82 Precision: % 90.6 Recall: % 90.57
For k: 7 
Accuracy: % 98.38 Precision: % 87.13 Recall: % 87.09
For k: 9 
Accuracy: % 97.96 Precision: % 83.78 Recall: % 83.74

Fold 2

For k: 1 
Accuracy: % 99.72 Precision: % 97.75 Recall: % 97.75
For k: 3 
Accuracy: % 99.23 Precision: % 93.89 Recall: % 93.88
For k: 5 
Accuracy: % 98.8 Precision: % 90.46 Recall: % 90.45
For k: 7 
Accuracy: % 98.32 Precision: % 86.7 Recall: % 86.66
For k: 9 
Accuracy: % 97.87 Precision: % 83.09 Recall: % 83.05

Fold 3

For k: 1 
Accuracy: % 99.65 Precision: % 97.21 Recall: % 97.21
For k: 3 
Accuracy: % 99.23 Precision: % 93.83 Recall: % 93.82
For k: 5 
Accuracy: % 98.79 Precision: % 90.34 Recall: % 90.34
For k: 7 
Accuracy: % 98.34 Precision: % 86.81 Recall: % 86.8
For k: 9 
Accuracy: % 97.9 Precision: % 83.34 Recall: % 83.32

Fold 4

For k: 1 
Accuracy: % 99

In [14]:
#everythings happend for normalize values on top part now we try the same without normalize values
df = df.sample(frac=1)
for i in range(5): # calculate this value for each fold
    X = np.array(df.drop(["Personality"],axis=1))
    y = np.array(df["Personality"].astype("int"))
    testx = list(np.array_split(X,5))
    testy = list(np.array_split(y,5))
    X_test = testx[i]
    y_test = testy[i]
    testx.pop(i)
    testy.pop(i)
    X_train = np.concatenate(testx)
    y_train = np.concatenate(testy)
    k_list=[1,3,5,7,9] #calculate this value for each k value
    print("\n\nFold {}".format(i+1))
    for k in k_list:
        prediction = K_Neighbors(X_train, X_test, k)
        matrix=confusion_matrix(y_test,prediction)
        evaluate(matrix,k)



Fold 1

For k: 1 
Accuracy: % 99.72 Precision: % 97.76 Recall: % 97.77
For k: 3 
Accuracy: % 99.39 Precision: % 95.1 Recall: % 95.11
For k: 5 
Accuracy: % 99.09 Precision: % 92.78 Recall: % 92.77
For k: 7 
Accuracy: % 98.78 Precision: % 90.29 Recall: % 90.28
For k: 9 
Accuracy: % 98.47 Precision: % 87.82 Recall: % 87.78

Fold 2

For k: 1 
Accuracy: % 99.71 Precision: % 97.68 Recall: % 97.69
For k: 3 
Accuracy: % 99.41 Precision: % 95.28 Recall: % 95.28
For k: 5 
Accuracy: % 99.04 Precision: % 92.36 Recall: % 92.33
For k: 7 
Accuracy: % 98.69 Precision: % 89.61 Recall: % 89.55
For k: 9 
Accuracy: % 98.37 Precision: % 87.04 Recall: % 86.97

Fold 3

For k: 1 
Accuracy: % 99.71 Precision: % 97.68 Recall: % 97.69
For k: 3 
Accuracy: % 99.37 Precision: % 95.0 Recall: % 95.0
For k: 5 
Accuracy: % 99.02 Precision: % 92.22 Recall: % 92.2
For k: 7 
Accuracy: % 98.67 Precision: % 89.43 Recall: % 89.39
For k: 9 
Accuracy: % 98.33 Precision: % 86.79 Recall: % 86.71

Fold 4

For k: 1 
Accuracy: % 

In [ ]:
#report
"""
I can make an inference by looking at my observations in the code I wrote.
For each fold, as the k value increases, the accuracy of the prediction decreases, 
but the recall and precision values approach each other.but I can't compare fold values ​​because I chose fold values 
over a scrambled dataframe.When I look at the normalized and initial values, I can say that the values are very close to each other, 
but with a small difference, the unnormalized values give a more accurate result."""